root: true
extends: airbnb
plugins:
- react
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
env:
  browser: true
  jest: true
rules:
  # no-param-reassign: [error, { props: false }]
  react/prefer-stateless-function: off
  react/jsx-filename-extension: off
